name: myscheme_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  google_generative_ai: ^0.4.1
  http: ^1.2.1
  flutter_tts: ^4.2.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_gemini: ^3.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  flutter_markdown: ^0.7.4
  flutter_dotenv: ^5.2.1
  lottie: ^3.2.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  vibration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/lottie/
    - assets/jan_yojana_logo.png.png